#!/usr/bin/env python3
"""Build the compact USA PlayStation catalog from a pinned OpenVGDB release."""

from __future__ import annotations

import argparse
import json
import re
import sqlite3
import tempfile
import urllib.request
import zipfile
from datetime import datetime
from pathlib import Path

OPENVGDB_VERSION = "v29.0"
OPENVGDB_URL = f"https://github.com/OpenVGDB/OpenVGDB/releases/download/{OPENVGDB_VERSION}/openvgdb.zip"
NON_RETAIL = re.compile(
    r"\((?:demo|beta|proto|sample|review code|trade demo|press kit)(?:\)|,)", re.I
)
DISC_AFTER_FIRST = re.compile(r"\(Disc [2-9](?:\)|,)", re.I)
MAGAZINE_DISC = re.compile(r"(?:Jampack|PlayStation Underground|Interactive CD Sampler)", re.I)


def slug(value: str) -> str:
    value = value.lower().replace("&", " and ")
    value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    return value or "untitled"


def year(value: str | None) -> int:
    if not value:
        return 0
    match = re.search(r"(?:19|20)\d{2}", value)
    return int(match.group()) if match else 0


def genres(value: str | None) -> list[str]:
    if not value:
        return []
    useful = []
    aliases = {"Action Adventure": "Adventure", "Role-Playing": "RPG"}
    for item in value.split(","):
        item = aliases.get(item.strip(), item.strip())
        if item and item not in useful and item not in {"General", "Other"}:
            useful.append(item)
    return useful[:4]


def load_rows(database: Path) -> list[dict[str, object]]:
    connection = sqlite3.connect(database)
    connection.row_factory = sqlite3.Row
    rows = connection.execute(
        """
        SELECT rel.releaseTitleName, rel.releaseDescription,
               rel.releaseDeveloper, rel.releaseGenre, rel.releaseDate,
               rel.releaseReferenceURL, rom.romFileName, rom.romLanguage
        FROM RELEASES rel
        JOIN ROMs rom ON rom.romID = rel.romID
        WHERE rom.systemID = 38
          AND rel.TEMPregionLocalizedName = 'USA'
          AND rom.romLanguage LIKE '%English%'
        """
    ).fetchall()

    candidates: dict[str, sqlite3.Row] = {}
    for row in rows:
        filename = row["romFileName"] or ""
        title = row["releaseTitleName"] or ""
        if NON_RETAIL.search(filename) or DISC_AFTER_FIRST.search(filename):
            continue
        if MAGAZINE_DISC.search(filename) or MAGAZINE_DISC.search(title):
            continue
        previous = candidates.get(title)
        # Prefer a source-backed description, then the least decorated retail dump.
        score = (bool(row["releaseDescription"]), -filename.count("("), filename)
        old_score = (
            bool(previous["releaseDescription"]),
            -(previous["romFileName"] or "").count("("),
            previous["romFileName"] or "",
        ) if previous else None
        if previous is None or score > old_score:
            candidates[title] = row

    used_ids: dict[str, int] = {}
    output = []
    for title, row in sorted(candidates.items(), key=lambda item: item[0].casefold()):
        base_id = slug(title)
        used_ids[base_id] = used_ids.get(base_id, 0) + 1
        record_id = base_id if used_ids[base_id] == 1 else f"{base_id}-{used_ids[base_id]}"
        description = (row["releaseDescription"] or "").strip() or None
        output.append({
            "id": record_id,
            "title": title,
            "year": year(row["releaseDate"]),
            "genres": genres(row["releaseGenre"]),
            "description": description,
            "descriptionSource": row["releaseReferenceURL"] if description else None,
            "developer": (row["releaseDeveloper"] or "").strip() or None,
            "coverName": re.sub(r"\.cue$", "", row["romFileName"], flags=re.I),
        })
    return output


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    arguments = parser.parse_args()
    with tempfile.TemporaryDirectory() as temporary:
        archive = Path(temporary) / "openvgdb.zip"
        urllib.request.urlretrieve(OPENVGDB_URL, archive)
        with zipfile.ZipFile(archive) as zipped:
            database_name = next(name for name in zipped.namelist() if name == "openvgdb.sqlite")
            zipped.extract(database_name, temporary)
        records = load_rows(Path(temporary) / database_name)

    payload = json.dumps(records, ensure_ascii=False, separators=(",", ":"))
    content = (
        "// Generated by scripts/import-openvgdb-ps1.py from OpenVGDB "
        f"{OPENVGDB_VERSION}. Do not hand-edit.\n"
        "// Descriptions retain their per-game reference URLs; missing copy stays missing.\n"
        "export type UsCatalogSeed = { id: string; title: string; year: number; "
        "genres: string[]; description: string | null; descriptionSource: string | null; "
        "developer: string | null; coverName: string };\n"
        f"export const usCatalog: UsCatalogSeed[] = {payload};\n"
    )
    arguments.output.write_text(content, encoding="utf-8")
    described = sum(bool(record["description"]) for record in records)
    print(f"Wrote {len(records)} USA retail games ({described} sourced descriptions) to {arguments.output}")


if __name__ == "__main__":
    main()
