#!/usr/bin/env python3
"""Resolve the translation manifest's target serials against the Redump PSX DAT.

The manifest names which disc a patch was built for; this turns that name into
the size and hashes GameStore checks before it writes a patched image. Only the
serials the manifest actually references are emitted, because the full DAT is
13,591 releases and roughly 3.9 MB and the repository is kept media-light.

The DAT is read from libretro's mirror of Redump, which republishes it verbatim
and is fetchable without a browser session. It is never committed.
"""

from __future__ import annotations

import argparse
import json
import re
import urllib.request
from pathlib import Path

REDUMP_DAT_URL = (
    "https://raw.githubusercontent.com/libretro/libretro-database/master"
    "/metadat/redump/Sony%20-%20PlayStation.dat"
)
GAME_BLOCK = re.compile(r"game \(\n(.*?)\n\)\n", re.S)
GAME_NAME = re.compile(r'^\tname "(.*?)"', re.M)
GAME_SERIAL = re.compile(r'^\tserial "(.*?)"', re.M)
DAT_VERSION = re.compile(r'^\tversion "(.*?)"', re.M)
ROM_ENTRY = re.compile(
    r'rom \( name "(?P<name>.*?)" size (?P<size>\d+) '
    r"crc (?P<crc>[0-9A-Fa-f]+) md5 (?P<md5>[0-9A-Fa-f]+) sha1 (?P<sha1>[0-9A-Fa-f]+)"
)
MANIFEST_TARGET = re.compile(r'release:\s*"(?P<release>.*?)",\s*serial:\s*"(?P<serial>.*?)"')


def wanted_targets(manifest: Path) -> list[tuple[str, str]]:
    """Release name plus serial, because neither identifies a disc on its own."""
    found = MANIFEST_TARGET.findall(manifest.read_text(encoding="utf-8"))
    return sorted(set(found))


def load_dat(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": "GameStore-catalog-import/1"})
    with urllib.request.urlopen(request) as response:
        return response.read().decode("utf-8", errors="replace")


def resolve(dat: str, targets: list[tuple[str, str]]) -> tuple[dict[tuple[str, str], dict[str, object]], str]:
    version_match = DAT_VERSION.search(dat)
    version = version_match.group(1) if version_match else "unknown"
    wanted = set(targets)
    found: dict[tuple[str, str], dict[str, object]] = {}
    for block in GAME_BLOCK.findall(dat):
        serial_match = GAME_SERIAL.search(block)
        if not serial_match:
            continue
        release = GAME_NAME.search(block).group(1)
        hits = [
            (release, serial.strip())
            for serial in serial_match.group(1).split(",")
            if (release, serial.strip()) in wanted
        ]
        if not hits:
            continue
        # A multi-track disc lists one rom entry per track. Only the data track
        # is ever patched, and Redump always lists it first.
        tracks = [match.groupdict() for match in ROM_ENTRY.finditer(block)]
        if not tracks:
            continue
        data_track = tracks[0]
        for key in hits:
            record = {
                "release": release,
                "serial": key[1],
                "track": data_track["name"],
                "tracks": len(tracks),
                "size": int(data_track["size"]),
                "crc32": data_track["crc"].lower(),
                "sha1": data_track["sha1"].lower(),
            }
            # The DAT repeats a release under alternate serial notations. That
            # is harmless while the hashes agree, and a real ambiguity if not.
            if key in found and found[key]["sha1"] != record["sha1"]:
                raise SystemExit(
                    f"{key[0]} / {key[1]} matches two Redump images with different "
                    "hashes; the manifest must name a unique disc."
                )
            found[key] = record
    return found, version


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("manifest", type=Path)
    parser.add_argument("output", type=Path)
    arguments = parser.parse_args()

    targets = wanted_targets(arguments.manifest)
    found, version = resolve(load_dat(REDUMP_DAT_URL), targets)
    missing = [key for key in targets if key not in found]
    if missing:
        raise SystemExit(
            "These manifest targets are not in the Redump PlayStation DAT, so a "
            "patch cannot be verified against them: "
            + ", ".join(f"{release} / {serial}" for release, serial in missing)
        )

    payload = json.dumps([found[key] for key in targets], ensure_ascii=False, indent=2)
    arguments.output.write_text(
        "// Generated by scripts/import-redump-targets.py from the Redump\n"
        f"// Sony - PlayStation DAT, version {version}. Do not hand-edit.\n"
        "// Only releases referenced by src/translationManifest.ts are included.\n"
        "export type RedumpTarget = {\n"
        "  release: string;\n"
        "  serial: string;\n"
        "  track: string;\n"
        "  tracks: number;\n"
        "  size: number;\n"
        "  crc32: string;\n"
        "  sha1: string;\n"
        "};\n"
        f"export const redumpDatVersion = {json.dumps(version)};\n"
        f"export const redumpTargets: RedumpTarget[] = {payload};\n",
        encoding="utf-8",
    )
    print(f"Resolved {len(found)}/{len(targets)} manifest targets against Redump {version}")


if __name__ == "__main__":
    main()
