import { useEffect, useMemo, useRef, useState } from 'react';
import { ChevronDown, ExternalLink, Gamepad2, Heart, Library, Play, Search, Settings2, Sparkles, Star, X } from 'lucide-react';
import { facetOrder, games, Game } from './catalog';

type Sort='curated'|'title'|'year-new'|'year-old';
const open=(url:string)=>window.gameStore?.openExternal(url) ?? window.open(url,'_blank','noopener');
const loadFavs=()=>{try{return new Set<string>(JSON.parse(localStorage.getItem('gamestore:favorites')||'[]'))}catch{return new Set<string>()}};

export function App(){
 const [query,setQuery]=useState(''); const [region,setRegion]=useState('All regions'); const [genre,setGenre]=useState('All genres');
 const [facet,setFacet]=useState('All flavors'); const [translation,setTranslation]=useState(false); const [sort,setSort]=useState<Sort>('curated');
 const [selected,setSelected]=useState<string|null>(null); const [favorites,setFavorites]=useState<Set<string>>(loadFavs); const [saved,setSaved]=useState(false);
 const detailsRef=useRef<HTMLDivElement>(null);
 const genres=useMemo(()=>Array.from(new Set(games.flatMap(g=>g.genres))).sort(),[]);
 const filtered=useMemo(()=>games.filter(g=>{
   const text=`${g.title} ${g.description} ${g.genres.join(' ')} ${g.facets.join(' ')}`.toLowerCase();
   return (!query||text.includes(query.toLowerCase()))&&(region==='All regions'||g.region===region)&&(genre==='All genres'||g.genres.includes(genre))&&(facet==='All flavors'||g.facets.includes(facet))&&(!translation||!!g.translation);
 }).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):sort==='year-new'?b.year-a.year:sort==='year-old'?a.year-b.year:0),[query,region,genre,facet,translation,sort]);
 const groups=useMemo(()=>{const rows:Game[][]=[]; for(let i=0;i<filtered.length;i+=6) rows.push(filtered.slice(i,i+6)); return rows},[filtered]);
 const toggleFav=(id:string)=>setFavorites(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);localStorage.setItem('gamestore:favorites',JSON.stringify([...n]));return n});
 useEffect(()=>{if(selected)requestAnimationFrame(()=>detailsRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'}))},[selected]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null)};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
 const exportShelf=async()=>{const payload=JSON.stringify({version:1,exportedAt:new Date().toISOString(),favorites:[...favorites]},null,2);if(window.gameStore){await window.gameStore.saveExport(payload);setSaved(true);setTimeout(()=>setSaved(false),2500)}else{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([payload],{type:'application/json'}));a.download='GameStore-shelves.json';a.click()}};
 return <div className="app">
  <header><div className="brand"><div className="logo"><Gamepad2/></div><div><b>GAME<span>STORE</span></b><small>PLAY THE STRANGE STUFF</small></div></div><nav><button className="nav-active"><Library/>Discover</button><button onClick={()=>{setFacet('Surreal');setSelected(null)}}><Sparkles/>Weird picks</button><button onClick={()=>setTranslation(true)}><Play/>Translations</button></nav><button className="export" onClick={exportShelf}>{saved?'Saved to Documents':'Export shelf'}</button></header>
  <main>
   <section className="hero"><p className="eyebrow">CURATOR'S CUT · PLAYSTATION</p><h1>The delightful outer limits<br/>of the <i>original PlayStation.</i></h1><p>Thirty hand-picked games that took a wrong turn into brilliance. Official English releases and verified translation leads only.</p><div className="hero-stats"><b>{games.length}<small>CURATED GAMES</small></b><b>{games.filter(g=>g.translation).length}<small>TRANSLATIONS</small></b><b>{facetOrder.length}<small>WEIRD FLAVORS</small></b></div></section>
   <section className="shelves"><button onClick={()=>setFacet('Surreal')}><span>FEVER DREAMS</span><b>Surreal worlds</b><small>Reality is negotiable</small></button><button onClick={()=>setFacet('Genre collision')}><span>GENRE COLLISIONS</span><b>Beautiful accidents</b><small>Two games walk into one disc</small></button><button onClick={()=>setFacet('Experimental controls')}><span>HANDS, RECONSIDERED</span><b>Control experiments</b><small>Learning to move again</small></button><button onClick={()=>setTranslation(true)}><span>FOUND IN TRANSLATION</span><b>Japan's secret shelf</b><small>Playable in English</small></button></section>
   <section className="catalog-head"><div><p className="eyebrow">BROWSE THE CATALOG</p><h2>{filtered.length} games worth getting lost in</h2></div><div className="search"><Search/><input aria-label="Search games" placeholder="Search title, mood, mechanic…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')}><X/></button>}</div></section>
   <div className="filters"><Settings2/><select value={region} onChange={e=>setRegion(e.target.value)}><option>All regions</option><option>USA</option><option>Europe</option><option>Japan</option></select><select value={genre} onChange={e=>setGenre(e.target.value)}><option>All genres</option>{genres.map(x=><option key={x}>{x}</option>)}</select><select value={facet} onChange={e=>setFacet(e.target.value)}><option>All flavors</option>{facetOrder.map(x=><option key={x}>{x}</option>)}</select><label className="check"><input type="checkbox" checked={translation} onChange={e=>setTranslation(e.target.checked)}/> English patches</label><span className="spacer"/><select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="curated">Curator order</option><option value="title">Title A–Z</option><option value="year-new">Newest first</option><option value="year-old">Oldest first</option></select>{(query||region!=='All regions'||genre!=='All genres'||facet!=='All flavors'||translation)&&<button className="clear" onClick={()=>{setQuery('');setRegion('All regions');setGenre('All genres');setFacet('All flavors');setTranslation(false)}}>Clear all</button>}</div>
   <div className="grid-wrap">{groups.map((row,ri)=><div className="row" key={`${ri}-${row[0]?.id}`}>
    <div className="cards">{row.map(game=><GameCard key={game.id} game={game} selected={selected===game.id} favorite={favorites.has(game.id)} onFav={()=>toggleFav(game.id)} onOpen={()=>setSelected(selected===game.id?null:game.id)}/>)}</div>
    {row.some(g=>g.id===selected)&&<Detail ref={detailsRef} game={row.find(g=>g.id===selected)!} favorite={favorites.has(selected!)} onFav={()=>toggleFav(selected!)} onClose={()=>setSelected(null)}/>}</div>)}
    {!filtered.length&&<div className="empty"><Sparkles/><h2>Nothing lives in this exact corner.</h2><p>Clear a filter and let the oddities back in.</p></div>}
   </div>
  </main><footer><b>GameStore 0.1</b><span>Curated locally · No ROM files bundled · Sources open in your browser</span></footer>
 </div>
}

function GameCard({game,selected,favorite,onFav,onOpen}:{game:Game;selected:boolean;favorite:boolean;onFav:()=>void;onOpen:()=>void}){
 const [bad,setBad]=useState(false); return <article className={`card ${selected?'selected':''}`}><button className="cover" onClick={onOpen} aria-expanded={selected}>{game.cover&&!bad?<img src={game.cover} alt={`${game.title} cover`} loading="lazy" onError={()=>setBad(true)}/>:<div className="cover-fallback"><Gamepad2/><b>{game.title}</b></div>}<span className={`region ${game.region.toLowerCase()}`}>{game.region==='Europe'?'PAL':game.region==='USA'?'NTSC-U':'NTSC-J'}</span>{game.translation&&<span className="translated">EN PATCH</span>}<i><ChevronDown/></i></button><div className="card-title"><div><h3>{game.title}</h3><p>{game.year} · {game.genres.join(' / ')}</p></div><button aria-label="Favorite" className={favorite?'fav active':'fav'} onClick={onFav}><Heart fill={favorite?'currentColor':'none'}/></button></div></article>
}

import { forwardRef } from 'react';
const Detail=forwardRef<HTMLDivElement,{game:Game;favorite:boolean;onFav:()=>void;onClose:()=>void}>(({game,favorite,onFav,onClose},ref)=>{
 const [media,setMedia]=useState<'video'|'screens'>('video'); return <div className="detail" ref={ref}><div className="detail-top"><div><p className="eyebrow">{game.region} RELEASE · {game.year}</p><h2>{game.title}</h2><div className="tags">{[...game.genres,...game.facets].map(x=><span key={x}>{x}</span>)}</div></div><div className="detail-actions"><button className={favorite?'active':''} onClick={onFav}><Heart fill={favorite?'currentColor':'none'}/> {favorite?'Saved':'Save'}</button><button onClick={onClose}><X/> Close</button></div></div><div className="detail-body"><div className="copy"><p className="description">{game.description}</p><blockquote>“{game.curatorNote}”<small>— GameStore curator note</small></blockquote><dl><div><dt>Developer</dt><dd>{game.developer}</dd></div><div><dt>Players</dt><dd>{game.players}</dd></div><div><dt>Language</dt><dd>{game.translation?'English fan patch':'Official English'}</dd></div><div><dt>Release scope</dt><dd>{game.region} · PlayStation</dd></div></dl>{game.translation&&<div className="translation"><p className="eyebrow">TRANSLATION RECORD</p><b>{game.translation.status} English patch</b><span>{game.translation.team}</span><small>Required base: {game.translation.base}. Verify your disc hash against the patch documentation before applying.</small><button onClick={()=>open(game.translation!.url)}>Find patch details <ExternalLink/></button></div>}<div className="links"><p className="eyebrow">SOURCES</p>{game.links.map(l=><button key={l.url} onClick={()=>open(l.url)}><i className={l.state}/>{l.label}<span>{l.state}</span><ExternalLink/></button>)}</div></div><div className="media"><div className="media-tabs"><button className={media==='video'?'active':''} onClick={()=>setMedia('video')}>Gameplay video</button><button className={media==='screens'?'active':''} onClick={()=>setMedia('screens')}>Screenshots</button></div>{media==='video'?(game.video?<iframe src={game.video} title={`${game.title} gameplay`} allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:<div className="no-media"><Play/><h3>Video candidate needed</h3><p>No verified video has been curated for this release yet.</p><button onClick={()=>open(`https://www.youtube.com/results?search_query=${encodeURIComponent(game.title+' PS1 gameplay')}`)}>Search YouTube <ExternalLink/></button></div>):<div className="no-media"><Gamepad2/><h3>Screenshots need provenance</h3><p>No screenshot is being claimed as release-specific without a verified source.</p></div>}<p className="media-note">Media loads on demand from its original source. Release scope and attribution remain visible.</p></div></div></div>
});
