import { forwardRef, useEffect, useMemo, useRef, useState } from 'react';
import { ChevronDown, Compass, ExternalLink, Gamepad2, Grid2X2, Heart, Image, Library, Play, Search, Settings, Settings2, Sparkles, X } from 'lucide-react';
import { facetOrder, games, Game } from './catalog';

type Sort='curated'|'title'|'year-new'|'year-old';
type ArtCandidate={url:string;gameId:number;title:string;source:string};
const open=(url:string)=>window.gameStore?.openExternal(url) ?? window.open(url,'_blank','noopener');
const loadFavs=()=>{try{return new Set<string>(JSON.parse(localStorage.getItem('gamestore:favorites')||'[]'))}catch{return new Set<string>()}};
const preferredArt=(game:Game)=>localStorage.getItem(`gamestore:art:${game.id}`)||game.cover;

export function App(){
 const [query,setQuery]=useState(''); const [region,setRegion]=useState('All regions'); const [genre,setGenre]=useState('All genres');
 const [facet,setFacet]=useState('All flavors'); const [translation,setTranslation]=useState(false); const [sort,setSort]=useState<Sort>('curated');
 const [selected,setSelected]=useState<string|null>(null); const [favorites,setFavorites]=useState<Set<string>>(loadFavs); const [saved,setSaved]=useState(false); const [settings,setSettings]=useState(false); const [artVersion,setArtVersion]=useState(0);
 const detailsRef=useRef<HTMLDivElement>(null);
 const genres=useMemo(()=>Array.from(new Set(games.flatMap(g=>g.genres))).sort(),[]);
 const filtered=useMemo(()=>games.filter(g=>{const text=`${g.title} ${g.description} ${g.genres.join(' ')} ${g.facets.join(' ')}`.toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(region==='All regions'||g.region===region)&&(genre==='All genres'||g.genres.includes(genre))&&(facet==='All flavors'||g.facets.includes(facet))&&(!translation||!!g.translation)}).sort((a,b)=>sort==='title'?a.title.localeCompare(b.title):sort==='year-new'?b.year-a.year:sort==='year-old'?a.year-b.year:0),[query,region,genre,facet,translation,sort]);
 const groups=useMemo(()=>{const rows:Game[][]=[];for(let i=0;i<filtered.length;i+=6)rows.push(filtered.slice(i,i+6));return rows},[filtered]);
 const toggleFav=(id:string)=>setFavorites(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);localStorage.setItem('gamestore:favorites',JSON.stringify([...next]));return next});
 useEffect(()=>{if(selected)requestAnimationFrame(()=>detailsRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'}))},[selected]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSelected(null);setSettings(false)}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
 const exportShelf=async()=>{const payload=JSON.stringify({version:1,exportedAt:new Date().toISOString(),favorites:[...favorites]},null,2);if(window.gameStore){await window.gameStore.saveExport(payload);setSaved(true);setTimeout(()=>setSaved(false),2500)}};
 const reset=()=>{setQuery('');setRegion('All regions');setGenre('All genres');setFacet('All flavors');setTranslation(false)};
 return <div className="shell">
  <aside><div className="brand"><div className="logo"><Gamepad2/></div><b>GAME<span>STORE</span></b></div><nav><button className="active" onClick={reset}><Compass/>Discover</button><button><Gamepad2/>Platforms</button><button onClick={()=>setFacet('Surreal')}><Sparkles/>Weird Picks</button><button onClick={()=>setTranslation(true)}><Library/>Translations</button><button onClick={()=>setFacet('All flavors')}><Heart/>Favorites</button></nav><button className="settings-link" onClick={()=>setSettings(true)}><Settings/>Settings</button></aside>
  <div className="workspace"><header><div className="global-search"><Search/><input aria-label="Search games" placeholder="Search games, genres, moods…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')}><X/></button>}</div><button className="export" onClick={exportShelf}>{saved?'Saved':'Export shelf'}</button></header>
  <main><div className="platforms"><button className="active">All</button><button>PS1</button><button disabled>PS2</button><button disabled>Saturn</button><button disabled>Dreamcast</button><button disabled>GameCube</button><button disabled>PSP</button><span>PS1 preview catalog</span></div>
   <div className="filters"><Settings2/><select value={region} onChange={e=>setRegion(e.target.value)}><option>All regions</option><option>USA</option><option>Europe</option><option>Japan</option></select><select value={genre} onChange={e=>setGenre(e.target.value)}><option>All genres</option>{genres.map(x=><option key={x}>{x}</option>)}</select><select value={facet} onChange={e=>setFacet(e.target.value)}><option>All flavors</option>{facetOrder.map(x=><option key={x}>{x}</option>)}</select><label className="check"><input type="checkbox" checked={translation} onChange={e=>setTranslation(e.target.checked)}/> English patch</label><span className="spacer"/><select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="curated">Sort: Recommended</option><option value="title">Sort: Title</option><option value="year-new">Sort: Newest</option><option value="year-old">Sort: Oldest</option></select></div>
   <section className="feature"><div><p>CURATOR'S SHELF</p><h1>Beautifully Weird</h1><span>Surreal worlds, bad ideas, and brilliant accidents.</span></div><div className="feature-cards">{[games[3],games[0],games[4],games[1],games[5],games[6]].map(g=><MiniCover key={g.id} game={g} onClick={()=>{setSelected(g.id);setFacet('All flavors')}}/>)}</div></section>
   <div className="catalog-head"><div><h2>{filtered.length} PlayStation games</h2><p>USA first · PAL fallback · Japan exclusives with English patches</p></div><Grid2X2/></div>
   <div className="grid-wrap" key={artVersion}>{groups.map((row,ri)=><div className="row" key={`${ri}-${row[0]?.id}`}><div className="cards">{row.map(game=><GameCard key={game.id} game={game} selected={selected===game.id} favorite={favorites.has(game.id)} onFav={()=>toggleFav(game.id)} onOpen={()=>setSelected(selected===game.id?null:game.id)}/>)}</div>{row.some(g=>g.id===selected)&&<Detail ref={detailsRef} game={row.find(g=>g.id===selected)!} favorite={favorites.has(selected!)} onFav={()=>toggleFav(selected!)} onClose={()=>setSelected(null)} onArtChanged={()=>setArtVersion(v=>v+1)}/>}</div>)}{!filtered.length&&<div className="empty"><Sparkles/><h2>Nothing in this corner.</h2><button onClick={reset}>Clear filters</button></div>}</div>
  </main><footer><b>GameStore 0.3 preview</b><span>Media-light core · artwork fetched from attributed providers</span></footer></div>
  {settings&&<ProviderSettings onClose={()=>setSettings(false)}/>}</div>
}

function CoverImage({game}:{game:Game}){const [bad,setBad]=useState(false);const [ratio,setRatio]=useState('1 / 1');const src=preferredArt(game);return <div className="art-frame" style={{aspectRatio:ratio}}>{src&&!bad?<img src={src} alt={`${game.title} official release cover`} loading="lazy" onLoad={e=>setRatio(`${e.currentTarget.naturalWidth} / ${e.currentTarget.naturalHeight}`)} onError={()=>setBad(true)}/>:<div className="cover-fallback"><Gamepad2/><b>{game.title}</b><small>ART NOT DOWNLOADED</small></div>}</div>}
function MiniCover({game,onClick}:{game:Game;onClick:()=>void}){return <button className="mini-cover" onClick={onClick}><CoverImage game={game}/><span>{game.title}</span></button>}
function GameCard({game,selected,favorite,onFav,onOpen}:{game:Game;selected:boolean;favorite:boolean;onFav:()=>void;onOpen:()=>void}){return <article className={`card ${selected?'selected':''}`}><button className="cover" onClick={onOpen} aria-expanded={selected}><CoverImage game={game}/><span className="region">{game.region==='Europe'?'PAL':game.region==='USA'?'US':'JP'}</span>{game.translation&&<span className="translated">EN PATCH</span>}<i><ChevronDown/></i></button><div className="card-title"><div><h3>{game.title}</h3><p>{game.year} · {game.genres.join(' / ')}</p></div><button aria-label="Favorite" className={favorite?'fav active':'fav'} onClick={onFav}><Heart fill={favorite?'currentColor':'none'}/></button></div></article>}

const Detail=forwardRef<HTMLDivElement,{game:Game;favorite:boolean;onFav:()=>void;onClose:()=>void;onArtChanged:()=>void}>(({game,favorite,onFav,onClose,onArtChanged},ref)=>{
 const [media,setMedia]=useState<'video'|'screens'>('video');const [artOpen,setArtOpen]=useState(false);const [candidates,setCandidates]=useState<ArtCandidate[]>([]);const [artError,setArtError]=useState('');const [loading,setLoading]=useState(false);
 const findArt=async()=>{setArtOpen(true);setLoading(true);setArtError('');try{if(!window.gameStore)throw new Error('Artwork lookup is available in the desktop app.');setCandidates(await window.gameStore.findTheGamesDbArt(game.title))}catch(e){setArtError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};
 const applyArt=(url:string)=>{localStorage.setItem(`gamestore:art:${game.id}`,url);onArtChanged();setArtOpen(false)};
 return <div className="detail" ref={ref}><div className="detail-top"><div><p className="eyebrow">{game.region} · PLAYSTATION · {game.year}</p><h2>{game.title}</h2><div className="tags">{[...game.genres,...game.facets].map(x=><span key={x}>{x}</span>)}</div></div><div className="detail-actions"><button className={favorite?'active':''} onClick={onFav}><Heart fill={favorite?'currentColor':'none'}/>{favorite?'Saved':'Favorite'}</button><button onClick={onClose}><X/>Close</button></div></div><div className="detail-body"><div className="detail-art"><CoverImage game={game}/><button onClick={findArt}><Image/> Find official box art</button><small>Current source: {localStorage.getItem(`gamestore:art:${game.id}`)?'TheGamesDB override':'Libretro Thumbnails'}</small></div><div className="copy"><p className="description">{game.description}</p><blockquote>“{game.curatorNote}”</blockquote><dl><div><dt>Developer</dt><dd>{game.developer}</dd></div><div><dt>Players</dt><dd>{game.players}</dd></div><div><dt>Language</dt><dd>{game.translation?'English fan patch':'Official English'}</dd></div><div><dt>Release</dt><dd>{game.region} · {game.year}</dd></div></dl>{game.translation&&<button className="patch-button" onClick={()=>open(game.translation!.url)}>Get English patch <ExternalLink/></button>}<div className="links">{game.links.map(l=><button key={l.url} onClick={()=>open(l.url)}><i className={l.state}/>{l.label}<span>{l.state}</span><ExternalLink/></button>)}</div></div><div className="media"><div className="media-tabs"><button className={media==='video'?'active':''} onClick={()=>setMedia('video')}>Gameplay</button><button className={media==='screens'?'active':''} onClick={()=>setMedia('screens')}>Screenshots</button></div>{media==='video'&&game.video?<iframe src={game.video} title={`${game.title} gameplay`} allow="accelerometer; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:<div className="no-media"><Play/><h3>{media==='video'?'Video unavailable':'Screenshots not downloaded'}</h3><p>Media stays honest when no release-matched source is available.</p></div>}<p className="media-note">Loaded on demand from its attributed source.</p></div></div>{artOpen&&<div className="art-picker"><div><h3>Official box-art candidates</h3><button onClick={()=>setArtOpen(false)}><X/></button></div>{loading&&<p>Searching TheGamesDB…</p>}{artError&&<p className="error">{artError}</p>}<div className="candidate-grid">{candidates.map(c=><button key={c.url} onClick={()=>applyArt(c.url)}><img src={c.url} alt={c.title}/><span>{c.source} · Apply</span></button>)}</div></div>}</div>
});

function ProviderSettings({onClose}:{onClose:()=>void}){const [key,setKey]=useState('');const [saved,setSaved]=useState(false);useEffect(()=>{window.gameStore?.getTheGamesDbKey().then(setKey)},[]);const save=async()=>{await window.gameStore?.setTheGamesDbKey(key);setSaved(true);setTimeout(()=>setSaved(false),1800)};return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="settings-modal"><div><p className="eyebrow">MEDIA PROVIDERS</p><button onClick={onClose}><X/></button></div><h2>Artwork scrapers</h2><p>Libretro works without configuration. Add your TheGamesDB key to search official release artwork from each game’s detail panel.</p><label>TheGamesDB API key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Stored only on this machine"/></label><small>The key is encrypted with the operating system keychain when available and never enters exports or GitHub.</small><button className="save-provider" onClick={save}>{saved?'Saved':'Save provider key'}</button></section></div>}
