/**
 * Real filenames sampled from the Libretro Sony - PlayStation thumbnail index
 * (top-scoring candidates for every catalog title plus random distractors).
 * Kept small on purpose: the repository stays media-light and the matcher still
 * gets tested against the exact strings it has to disambiguate in production.
 */
export const thumbnailIndexSample: string[] = [
  "007 Racing (USA).png",
  "AbalaBurn (Japan).png",
  "Aces of the Air (USA).png",
  "Advan Racing (Japan).png",
  "All Star Racing (USA).png",
  "Andretti Racing (Japan).png",
  "Apocalypse (USA).png",
  "Aqua Paradise (Japan).png",
  "Aquanaut no Kyuujitsu 2 (Japan).png",
  "Arkanoid Returns (Japan).png",
  "Army Men - Team Assault (Europe) (En,Fr,De,Es,It).png",
  "Army Men - World War (USA).png",
  "Azito 2 (Japan).png",
  "Baldies (Europe).png",
  "Baldy Land (Japan).png",
  "Ballistic (USA).png",
  "Barbie - Explorer (USA).png",
  "Baroque - Yuganda Mousou (Japan) (Genteiban).png",
  "Baroque - Yuganda Mousou (Japan).png",
  "Baroque Syndrome (Japan).png",
  "Battle Stations (USA).png",
  "Beat Planet Music (Japan).png",
  "Bistro, The - Ryouri _ Wine no Shokunin-tachi (Japan).png",
  "Blam! Machinehead (Japan).png",
  "Blast Radius (USA).png",
  "Blaster Master - Blasting Again (USA).png",
  "Blaze _ Blade Busters (Japan).png",
  "Blockids (Europe).png",
  "Bomberman (Japan).png",
  "Bomberman (Japan, Asia).png",
  "Bomberman World (USA).png",
  "Bombing Islands, The (USA).png",
  "BoomBots (USA).png",
  "Bottom of the 9th (USA).png",
  "Bubble Bobble also featuring Rainbow Islands (Europe).png",
  "Bundesliga 2000 - Der Fussball-Manager (Germany).png",
  "BursTrick - Wake Boarding!! (Europe) (En,Fr,De).png",
  "C3 Racing - Car Constructors Championship (Europe) (En,Fr,De,Es,It) (Rev 1).png",
  "CTR - Crash Team Racing (Europe) (En,Fr,De,Es,It,Nl) (EDC).png",
  "CTR - Crash Team Racing (Europe) (En,Fr,De,Es,It,Nl).png",
  "Caesars Palace (Europe).png",
  "Chaos Control (Japan).png",
  "Charumera (Japan).png",
  "Checkmate II (Europe).png",
  "Chessmaster, The (Japan).png",
  "Choro Q (Japan).png",
  "Choro Q 3 (Japan).png",
  "Chou Aniki - Kyuukyoku Muteki Ginga Saikyou Otoko (Japan).png",
  "Colony Wars (USA).png",
  "Colony Wars - Vengeance (France).png",
  "Contra - Legacy of War (USA).png",
  "Cooly Skunk (Japan).png",
  "Crash Bandicoot Racing (Japan).png",
  "Critical Depth (USA).png",
  "Criticom (USA).png",
  "Crossroad Crisis (USA).png",
  "Crow, The - City of Angels (USA).png",
  "D (Germany) (Disc 3).png",
  "Dance Dance Revolution (Japan).png",
  "Dancing Blade Katte ni Momotenshi! (Japan) (Disc 2).png",
  "Dangan (Japan).png",
  "Dare Devil Derby 3D (USA).png",
  "Darius Gaiden (Japan).png",
  "Darkstone (USA).png",
  "Demo One (Version 6) (Europe, Australia) (En,Fr,De,Es,It).png",
  "Destruction Derby (Japan).png",
  "Devil Dice (Europe) (En,Fr,De,Es,It).png",
  "Devil Dice (USA).png",
  "Devil Man (Japan).png",
  "Devil's Deception (Europe) (En,Fr,De).png",
  "Dino Crisis (Europe).png",
  "Dino Crisis (Japan).png",
  "Dino Crisis (USA).png",
  "Dino Crisis 2 (USA).png",
  "Disney's Treasure Planet (USA).png",
  "Disney-Pixar A Bug's Life - Megaminimondo (Italy) (Rev 1).png",
  "Disneys Atlantis - Das Geheimnis der verlorenen Stadt (Germany).png",
  "Dog Master, The (Japan).png",
  "Doom (USA).png",
  "Dragon Quest VII - Eden no Senshi-tachi (Japan) (Rev 1).png",
  "DragonHeart - Fire _ Steel (USA).png",
  "Eagle One - Harrier Attack (USA) (En,Fr,Es).png",
  "Eggs of Steel - Charlie's Eggcellent Adventure (USA).png",
  "Elan (Japan).png",
  "Elan Plus (Japan).png",
  "Eternal Melody (Japan).png",
  "Evil Zone (Europe).png",
  "F.A. Premier League Stars, The (Europe).png",
  "Famires, The (Japan).png",
  "Fantastic Four (USA).png",
  "Final Fantasy VII International (Japan).png",
  "Formula One 2000 (USA).png",
  "Formula One 99 (USA, Canada) (En,Fr,Es).png",
  "Front Mission Alternative (Japan).png",
  "Future Cop - L.A.P.D. (Germany).png",
  "G-Police (Japan) (Disc 2).png",
  "G-Police (USA).png",
  "G. Darius + Devil Dice + Brunswick Circuit Pro Bowling (USA).png",
  "Game no Tatsujin 2 (Japan).png",
  "GeGeGe no Kitarou (Japan).png",
  "Gekiretsu Pachinkers (Japan).png",
  "Gekitou! Crush Gear Turbo (Japan).png",
  "Germs - Nerawareta Machi (Japan).png",
  "Ghoul Panic (Europe) (En,Fr,De,Es,It).png",
  "Gionbana (Japan).png",
  "Gran Turismo (USA).png",
  "Gunbalina (Japan).png",
  "Gunbarl (Japan, Asia).png",
  "Gungage (Japan).png",
  "Hamster Monogatari (Japan).png",
  "Happy Diet (Japan).png",
  "Happy Hotel (Japan).png",
  "Happy Jogging in Hawaii (Japan).png",
  "Happy Salvage (Japan).png",
  "Happy Salvage - Otakara Disc (Japan).png",
  "Harmful Park (Japan).png",
  "Heart of Darkness (USA) (Disc 1).png",
  "Heaven's Gate (Japan).png",
  "Hermie Hopperhead - Scrap Panic (Japan).png",
  "Hogs of War (Europe).png",
  "Hogs of War (USA).png",
  "Hoshi no Oka Gakuen Monogatari - Gakuensai (Japan).png",
  "Hybrid (Europe).png",
  "Hyper Securities 2 (Japan).png",
  "Iblard - Laputa no Kaeru Machi (Japan).png",
  "Imadoki no Vampire - Bloody Bride (Japan).png",
  "Impact Racing (Japan).png",
  "Incredible Crisis (Europe) (En,Fr,De,Es,It).png",
  "Incredible Crisis (USA).png",
  "Incredible Hulk, The - The Pantheon Saga (USA).png",
  "International Moto-X (Japan).png",
  "Irritating Stick (USA).png",
  "Jersey Devil (Europe) (En,Fr,De).png",
  "Jersey Devil (USA).png",
  "Jungle Park (Japan).png",
  "K-1 Revenge (USA).png",
  "Kattobi Tune (Japan).png",
  "Kickboxing (USA).png",
  "Kid Mix Section - Character Collection (Japan).png",
  "Kids Station - Hitori de Dekiru mon! (Japan) (Controller Set).png",
  "Kitchen Panic (Japan).png",
  "Knockout Kings (USA).png",
  "Kokumeikan (Japan).png",
  "Kowloon's Gate (Japan) (Special Disc).png",
  "Kowloon's Gate - Kowloon Fuusuiden (Japan) (Disc 1) (Byakko).png",
  "Kowloon's Gate - Kowloon Fuusuiden (Japan) (Disc 4) (Seiryuu).png",
  "Kowloon's Gate - Kowloon Fuusuiden (Japan, Asia) (Disc 1) (Byakko).png",
  "Kowloon's Gate - Kowloon Fuusuiden (Japan, Asia) (Disc 2) (Genbu).png",
  "Kowloon's Gate - Kowloon Fuusuiden (Japan, Asia) (Disc 3) (Suzaku).png",
  "Kowloon's Gate - Kowloon Fuusuiden (Japan, Asia) (Disc 4) (Seiryuu).png",
  "Kowloon's Gate - Kowloon Fuusuiden (Japan, Asia).png",
  "Kowloon-jou (Japan).png",
  "KulaQuest (Japan).png",
  "Kuru Kuru Panic (Japan).png",
  "Kyuukyoku no Soukoban (Japan).png",
  "Lagnacure (Japan, Asia).png",
  "Legend of Legaia (USA).png",
  "Lemmings _ Oh No! More Lemmings (USA).png",
  "Linda^3 Again (Japan) (Rev 1).png",
  "Linda^3 Again (Japan).png",
  "London Seirei Tanteidan (Japan).png",
  "Mad Panic Coaster (Japan).png",
  "Mad Stalker - FullMetalForce (Japan).png",
  "Marvel vs. Capcom - Clash of Super Heroes - EX Edition (Japan).png",
  "MaxRacer (Japan).png",
  "Medal of Honor (USA).png",
  "Medarot R (Japan).png",
  "MediEvil (Europe).png",
  "MediEvil (USA).png",
  "Meitantei Conan (Japan).png",
  "MeltyLancer - The 3rd Planet (Japan) (Disc 1).png",
  "Meremanoid (Japan).png",
  "Metal Gear Solid - Integral (Japan, Asia) (Disc 3) (VR-Disc).png",
  "Metamor Panic - Doki Doki Youma Busters!! (Japan).png",
  "Micro Machines (Japan).png",
  "Minna no Golf 2 (Japan).png",
  "Mizzurna Falls (Japan).png",
  "Monopoly (Japan).png",
  "Monopoly (USA).png",
  "Monster Farm 2 (Japan) (Rev 1).png",
  "MonsterSeed (Japan).png",
  "Mori no Oukoku (Japan).png",
  "Morita Kazurou no Reversi (Japan).png",
  "Mr. Driller (USA).png",
  "Mr. Driller G (Japan).png",
  "Mushitarou (Japan).png",
  "NASCAR 98 (Japan).png",
  "NCAA Final Four 99 (USA).png",
  "NHL Blades of Steel 2000 (USA).png",
  "Neo Planet (Japan).png",
  "Nick Jr. Dora the Explorer - Barnyard Buddies (Europe).png",
  "Nickelodeon Rocket Power - Team Rocket Rescue (Europe).png",
  "Nicktoons Racing (USA).png",
  "No One Can Stop Mr. Domino (Europe).png",
  "No One Can Stop Mr. Domino (USA).png",
  "Oh No! (Japan).png",
  "Omega Boost (USA).png",
  "One (Europe) (En,Fr,De,Es,It).png",
  "One (Japan).png",
  "One (USA).png",
  "One Piece Mansion (Europe).png",
  "One Piece Mansion (Japan).png",
  "One Piece Mansion (USA).png",
  "Ore no Ryouri (Japan).png",
  "Ore! Tomba (Japan).png",
  "Otona no Asobi (Japan).png",
  "PO'ed (USA).png",
  "PaRappa the Rapper (Japan).png",
  "Paca Paca Passion (Japan).png",
  "Paca Paca Passion Special (Japan).png",
  "Pachinko Dream (Japan).png",
  "Paranoia Scape (Japan).png",
  "Parasite Eve (Japan).png",
  "Parasite Eve II (Europe) (Disc 2).png",
  "Patriotic Pinball (USA).png",
  "Pepsiman (Japan).png",
  "Persona 2 - Eternal Punishment (USA).png",
  "Pitball (Japan).png",
  "Planet Dob (Japan).png",
  "Planet Laika (Japan).png",
  "Planet of the Apes (Europe) (En,Fr,De,Es,It).png",
  "Planet of the Apes (USA).png",
  "PoPoRoGue (Japan) (Rev 1).png",
  "PoPoRoGue (Japan) (Yokokuban).png",
  "PoPoRoGue (Japan).png",
  "Pocket Family - Happy Family Plan (Japan).png",
  "Pocket Jiman (Japan).png",
  "Powerslave (USA).png",
  "Poy Poy (Europe).png",
  "Poy Poy (USA).png",
  "Poy Poy 2 (Europe).png",
  "Prismaticallization (Japan).png",
  "Queen's Road (Japan).png",
  "Quiz$Millionaire (Japan) (PSone Books).png",
  "Quiz$Millionaire (Japan).png",
  "R-Types (USA).png",
  "Racing (USA) (En,Fr,Es).png",
  "Racing Lagoon (Japan, Asia).png",
  "Rage Racer (Japan).png",
  "Rayman (Japan).png",
  "Rayman Brain Games (USA).png",
  "ReBoot (Europe).png",
  "ReBoot (USA).png",
  "Real Robot Sensen (Japan).png",
  "Remote Control Dandy (Japan).png",
  "Resident Evil (Germany).png",
  "Rhythm 'N' Face (Japan).png",
  "Rhythm Beat (Europe).png",
  "Riot (Europe).png",
  "Rising Zan - The Samurai Gunman (Europe) (En,Fr,De,Es,It).png",
  "Rising Zan - The Samurai Gunman (Japan).png",
  "Rising Zan - The Samurai Gunman (USA).png",
  "Risk (Europe) (En,Fr,De,Es).png",
  "Robotron X (Europe).png",
  "Robotron X (Japan).png",
  "Rockman (Japan).png",
  "Saikyou Ginsei Chess (Japan).png",
  "Saikyou Ginsei Mahjong (Japan).png",
  "Saikyou Ginsei Shougi (Japan).png",
  "Saikyou Toudai Shougi (Japan).png",
  "Saikyou Toudai Shougi 2 (Japan).png",
  "Saikyou no Igo (Japan).png",
  "Saikyou no Shougi (Japan).png",
  "Samurai Shodown - Warriors Rage (USA).png",
  "Samurai Shodown III (Europe).png",
  "Samurai Shodown III - Blades of Blood (USA).png",
  "Seiken Densetsu - Legend of Mana (Japan, Asia).png",
  "Senran (Japan).png",
  "Sensible Soccer (Europe) (En,Fr,De,Es,It,Nl).png",
  "Shin Megami Tensei II (Japan) (Rev 1).png",
  "Shin Theme Park (Japan).png",
  "Shockwave Assault (USA) (Disc 2) (Shockwave - Operation Jumpgate).png",
  "Shougi Saikyou 2 (Japan).png",
  "Sidewinder (Japan).png",
  "Silent Bomber (USA).png",
  "SimTheme Park (USA).png",
  "Simple 1500 Series Vol. 11 - The Pinball 3D (Japan).png",
  "Slap Happy Rhythm Busters (Japan).png",
  "Slots (USA).png",
  "Snowman, The (Japan).png",
  "Sol Divide (USA).png",
  "Soul of the Samurai (USA).png",
  "Soulmaster (Japan).png",
  "South Park (Europe).png",
  "South Park (USA).png",
  "Space Debris (Europe).png",
  "Spawn - The Eternal (Japan).png",
  "Spec Ops - Airborne Commando (USA).png",
  "Steel Harbinger (USA).png",
  "Steel Reign (USA).png",
  "Street Fighter Collection (Japan) (Disc 2).png",
  "Street Scooters (Japan).png",
  "Tail Concerto (USA).png",
  "Tail of the Sun (USA).png",
  "Tales of Destiny (USA).png",
  "Tales of Phantasia (USA).png",
  "Team Buddies (Europe) (En,Es,It).png",
  "Team Buddies (Europe) (En,Fr,De).png",
  "Team Buddies (USA).png",
  "Tenkuu no Restaurant (Japan).png",
  "Tenshi na Konamaiki (Japan).png",
  "Theme Park (Europe) (En,Fr,De,Es,Sv).png",
  "Theme Park (Japan).png",
  "Theme Park (USA).png",
  "Theme Park World (Japan).png",
  "Threads of Fate (USA).png",
  "Time Commando (Japan).png",
  "Time Crisis (Europe) (En,Fr,De).png",
  "Time Crisis (USA).png",
  "Tobal 2 (Japan, Asia).png",
  "Tobal No. 1 (Europe).png",
  "Tobal No. 1 (Japan).png",
  "Tobal No. 1 (USA).png",
  "Tokimeki Memorial Drama Series Vol. 3 - Tabidachi no Uta (Japan) (Disc 2).png",
  "Tomba! (USA).png",
  "Toushinden (Japan).png",
  "Treasures of the Deep (USA).png",
  "Unholy War, The (Europe) (En,Fr,De,Es,It).png",
  "Unholy War, The (USA).png",
  "Uprising X (USA).png",
  "VMX Racing (USA).png",
  "Valkyrie Profile (USA).png",
  "Vib-Ribbon (Europe) (En,Fr,De,Es,It).png",
  "Vib-Ribbon (Japan).png",
  "Viewpoint (USA).png",
  "Virtual Gallop - Kishudou (Japan).png",
  "WWF War Zone (USA).png",
  "Wai Wai Bowling (Japan).png",
  "Walt Disney Ksiega Dzungli - Groove Party (Poland).png",
  "War Gods (Europe).png",
  "War Gods (USA).png",
  "Wheel of Fortune (USA).png",
  "Whizz (Japan).png",
  "Wing Commander III - Heart of the Tiger (USA) (Disc 3).png",
  "Wizardry Empire II - Oujo no Isan (Japan).png",
  "X-Files, The (France) (Disc 4).png",
  "X.Racing (Japan).png",
  "X2 - No Relief (Japan).png",
  "Xenogears (Japan) (Disc 1).png",
  "Yu-Gi-Oh! Monster Capsule Breed _ Battle (Japan).png",
  "Yuukyuu Gensoukyoku Ensemble (Japan).png",
  "iS - Internal Section (Japan).png",
];
