export type LinkState = 'verified' | 'unverified' | 'stale' | 'dead';
export type Game = {
  id:string; title:string; year:number; region:'USA'|'Europe'|'Japan'; genres:string[]; facets:string[];
  description:string; curatorNote:string; cover?:string; screenshots?:string[]; video?:string;
  players:string; developer:string; rating?:{source:string;score:number;count?:number};
  translation?:{team:string;status:string;url:string;base:string}; links:{label:string;url:string;state:LinkState}[];
};
const lib=(name:string)=>`https://raw.githubusercontent.com/libretro-thumbnails/Sony_-_PlayStation/master/Named_Boxarts/${encodeURIComponent(name)}.png`;
const yt=(id:string)=>`https://www.youtube.com/embed/${id}`;
const wiki=(q:string)=>`https://en.wikipedia.org/wiki/Special:Search?search=${encodeURIComponent(q)}`;
const patch=(q:string)=>`https://www.romhacking.net/?page=translations&search=${encodeURIComponent(q)}`;
const g=(id:string,title:string,year:number,region:Game['region'],genres:string[],facets:string[],description:string,note:string,players='1',developer='Various',coverName?:string,video?:string,translation?:Game['translation']):Game=>({id,title,year,region,genres,facets,description,curatorNote:note,players,developer,cover:coverName?lib(coverName):undefined,video:video?yt(video):undefined,translation,rating:undefined,links:[{label:'Game reference',url:wiki(title),state:'verified'},...(translation?[{label:'Find translation patch',url:translation.url,state:'unverified' as LinkState}]:[])]});

export const games:Game[]=[
g('incredible-crisis','Incredible Crisis',2000,'USA',['Action','Minigame'],['Frantic comedy','Bizarre premise'],'A family attempts to reach grandma’s birthday while dancing, fleeing boulders, surviving bank robberies, and meeting aliens.','A mundane errand mutates into a delirious game-show catastrophe.','1','Polygon Magic','Incredible Crisis (USA)','JmL-47bMyjY'),
g('mr-domino','No One Can Stop Mr. Domino!',1998,'USA',['Puzzle','Action'],['Experimental controls','Bizarre premise'],'Lay dominoes around looping household courses, then trigger elaborate environmental chain reactions.','Domino toppling treated with the gravity of an extreme sport.','1','Artdink','No One Can Stop Mr. Domino! (USA)'),
g('vib-ribbon','Vib-Ribbon',2000,'Europe',['Rhythm'],['Minimalist','Experimental controls'],'Guide a wireframe rabbit through rhythm obstacles, including levels generated from your own audio CDs.','A black-and-white music visualizer escaped and became a perfect arcade game.','1','NanaOn-Sha','Vib-Ribbon (Europe)'),
g('tail-sun','Tail of the Sun',1997,'USA',['Adventure','Simulation'],['Surreal','Outsider art'],'Lead sleepy cavemen across a huge prehistoric landscape, gathering food and mammoth tusks to build a tower to the sun.','Its systems feel half anthropology, half dream logic.','1','Artdink','Tail of the Sun (USA)'),
g('rising-zan','Rising Zan: The Samurai Gunman',1999,'USA',['Action'],['Camp','Genre collision'],'A swaggering cowboy samurai slices robot ninjas, plays guitar, and poses his way through tokusatsu chaos.','It commits to its stupid brilliance with magnificent confidence.','1','UEP Systems','Rising Zan - The Samurai Gunman (USA)'),
g('irritating-stick','Irritating Stick',1999,'USA',['Puzzle'],['Strange peripheral','Experimental controls'],'Guide a stick through electrified mazes without touching the walls while a host narrates your failure.','A steady-hand carnival game engineered into concentrated anxiety.','1-2','Saurus','Irritating Stick (USA)'),
g('one-piece-mansion','One Piece Mansion',2001,'USA',['Puzzle','Simulation'],['Bizarre premise'],'Manage an apartment building where every tenant’s happiness affects neighboring rooms.','Landlordship reimagined as a spatial emotional-pressure puzzle.','1','Capcom','One Piece Mansion (USA)'),
g('devil-dice','Devil Dice',1998,'USA',['Puzzle'],['Bizarre premise'],'Tiny devils sprint across giant dice, rolling matching faces together before the board overwhelms them.','A sharp puzzle design wearing a wonderfully unhelpful demonic costume.','1-5','Shift','Devil Dice (USA)'),
g('team-buddies','Team Buddies',2000,'Europe',['Strategy','Action'],['Camp','Genre collision'],'Stack supply crates to manufacture foul-mouthed blob soldiers, weapons, and vehicles.','Toybox tactics with the vocabulary of a particularly rude pub.','1-4','Psygnosis','Team Buddies (Europe)'),
g('unholy-war','The Unholy War',1998,'USA',['Fighting','Strategy'],['Genre collision','Mascot nightmare'],'Arena combat and turn-based strategy collide with a bomb monkey, giant tick, and psychic war machines.','A roster assembled by tipping an entire sketchbook down the stairs.','1-2','Toys for Bob','Unholy War, The (USA)'),
g('poy-poy','Poy Poy',1997,'USA',['Action','Party'],['Frantic comedy'],'Cute contestants hurl rocks, logs, missiles, and scenery at one another in compact arenas.','Four-player friendship demolition in its purest 32-bit form.','1-4','Konami','Poy Poy (USA)'),
g('eggs-steel','Eggs of Steel',1998,'USA',['Platformer'],['Bizarre premise','Mascot nightmare'],'A walking egg explores a steel mill using deliberately weighty, awkward movement.','Industrial labor has never been so ovular.','1','Rhino Studios','Eggs of Steel - Charlie\'s Eggcellent Adventure (USA)'),
g('boombots','BoomBots',1999,'USA',['Fighting'],['Camp','Outsider art'],'A claymation brawler starring an Elvis alien, a fighting chicken, and rejected action figures.','The Neverhood’s mutant cousin picks a fight in a parking lot.','1-2','The Neverhood','BoomBots (USA)'),
g('harmful-park','Harmful Park',1997,'Japan',['Shooter'],['Cute horror','Bizarre premise'],'A bright cute-em-up firing pie, ice cream, and jelly through a weaponized amusement park.','Dessert artillery makes the apocalypse look adorable.','1-2','Sky Think System',undefined,undefined,{team:'LIPEMCO! Translations','status':'Complete','url':patch('Harmful Park'),base:'Japan SLPS-00498'}),
g('planet-laika','Planet Laika',1999,'Japan',['RPG'],['Surreal','Experimental RPG'],'A dog-headed colony on Mars is navigated through three personalities with different psychic powers.','A psychology textbook processed through a canine fever dream.','1','Quintet',undefined,undefined,{team:'Fan translation','status':'Complete','url':patch('Planet Laika'),base:'Japan SLPM-86264'}),
g('racing-lagoon','Racing Lagoon',1999,'Japan',['Racing','RPG'],['Genre collision','Camp'],'Square’s street-racing RPG turns night driving into operatic melodrama and car-part progression.','Every gear change feels like a forbidden monologue.','1','Square',undefined,undefined,{team:'Hilltop Works','status':'Complete','url':patch('Racing Lagoon'),base:'Japan SLPS-02038'}),
g('mizzurna-falls','Mizzurna Falls',1998,'Japan',['Adventure'],['Uncanny','Experimental controls'],'An ambitious open-town mystery follows a missing girl through a snowy small town with a living schedule.','Twin Peaks energy inside hardware that can barely contain the town.','1','Human Entertainment',undefined,undefined,{team:'Fan translation','status':'Complete','url':patch('Mizzurna Falls'),base:'Japan SLPS-01783'}),
g('paranoiascape','ParanoiaScape',1998,'Japan',['Pinball','Horror'],['Genre collision','Outsider art'],'Screaming Mad George turns first-person pinball into a biomechanical horror tunnel.','Horror pinball: two words that should have met much sooner.','1','Jorudan',undefined,undefined,{team:'Aeon Genesis','status':'Complete','url':patch('ParanoiaScape'),base:'Japan SLPS-01375'}),
g('baroque','Baroque',1999,'Japan',['RPG','Roguelike'],['Surreal','Body horror'],'Descend a mutating tower where death, guilt, angels, and distorted flesh form the progression loop.','A bleak roguelike whose lore seems to resent being understood.','1','Sting',undefined,undefined,{team:'Fan translation','status':'Complete','url':patch('Baroque PS1'),base:'Japan SLPM-86328'}),
g('remote-control-dandy','Remote Control Dandy',1999,'Japan',['Action','Simulation'],['Experimental controls','Bizarre premise'],'Control a giant robot from a human-scale viewpoint with intentionally cumbersome limb inputs.','The buildings are fragile and your controller is basically a forklift license.','1','Human Entertainment',undefined,undefined,{team:'Fan translation','status':'Complete','url':patch('Remote Control Dandy'),base:'Japan SLPS-02243'}),
g('tobal-2','Tobal No. 2',1997,'Japan',['Fighting','RPG'],['Genre collision'],'A technical fighter expands into dungeon crawling, monster capture, and a huge Toriyama-designed roster.','A fighting game swallowed an RPG and somehow improved its posture.','1-2','DreamFactory',undefined,undefined,{team:'Infinite Lupine','status':'Complete','url':patch('Tobal No. 2'),base:'Japan SLPS-01025'}),
g('germs','Germs: Nerawareta Machi',1999,'Japan',['RPG','Horror'],['Uncanny','Surreal'],'A first-person open-town RPG investigates alien parasites in a city collapsing into low-poly nightmare.','It feels like the PS1 itself caught an infection.','1','Koei',undefined,undefined,{team:'Fan translation','status':'Complete','url':patch('Germs Nerawareta Machi'),base:'Japan SLPS-02107'}),
g('kowloons-gate','Kowloon’s Gate',1997,'Japan',['Adventure'],['Surreal','Uncanny'],'Explore an Asian-gothic cyberpunk maze of cursed architecture, displaced objects, and impossible neighborhoods.','A pre-rendered city dreams that you are trespassing.','1','Zeque',undefined,undefined,{team:'Hilltop / Cargodin / EsperKnight','status':'Complete','url':patch('Kowloon Gate'),base:'Japan multi-disc release'}),
g('linda-cube','Linda³ Again',1997,'Japan',['RPG'],['Surreal','Dark comedy'],'Capture animals before an apocalypse while three scenarios veer through cloning, murder, and black comedy.','Pokémon’s deeply alarming aunt arrives with an evacuation plan.','1','Alfa System',undefined,undefined,{team:'Fan translation','status':'Complete','url':patch('Linda Cube Again'),base:'Japan SCPS-45124'}),
g('ore-no-ryouri','Ore no Ryouri',1999,'Japan',['Simulation','Action'],['Experimental controls','Frantic comedy'],'Use both analog sticks to chop, fry, pour, wash dishes, and repel restaurant disasters.','The finest cooking game ever made by people who hate calm wrists.','1-2','SCEI',undefined,undefined,{team:'Hilltop Works','status':'Complete','url':patch('Ore no Ryouri'),base:'Japan SCPS-10099'}),
g('pepsiman','Pepsiman',1999,'Japan',['Action'],['Camp','Mascot nightmare'],'Pepsi’s chrome superhero runs through traffic and catastrophe between live-action soda interludes.','Corporate advertising achieves outsider-art transcendence.','1','KID'),
g('cho-aniki','Cho Aniki: Kyuukyoku Muteki Ginga Saikyou Otoko',1995,'Japan',['Shooter'],['Camp','Body horror'],'A shooter powered by flexing bodybuilders, flying heads, protein, and interstellar posing.','A funding decision no committee will ever successfully reconstruct.','1-2','NCS'),
g('mad-panic-coaster','Mad Panic Coaster',1997,'Japan',['Shooter','Action'],['Frantic comedy','Bizarre premise'],'Ride a roller coaster through monsters and hazards while shooting and dodging at absurd speed.','A haunted dark ride tears loose from the amusement park.','1','Hakuhodo'),
g('internal-section','Internal Section',1999,'Japan',['Shooter','Rhythm'],['Surreal','Minimalist'],'A psychedelic tube shooter dives through abstract wireframe spaces synchronized to electronic music.','Rez’s strange PS1 ancestor, recovered from a laser-lit hard drive.','1','Square'),
g('slap-happy','Slap Happy Rhythm Busters',2000,'Japan',['Fighting','Rhythm'],['Genre collision','Camp'],'Cel-shaded street fighters trigger rhythm-button supers over a superb electronic soundtrack.','A club flyer became a fighting game and refused to sober up.','1-2','Polygon Magic')
];

export const facetOrder=['Surreal','Bizarre premise','Genre collision','Experimental controls','Camp','Uncanny','Frantic comedy','Mascot nightmare','Outsider art','Body horror','Minimalist'];
