// Generated by scripts/import-redump-targets.py from the Redump
// Sony - PlayStation DAT, version 2026.08.01. Do not hand-edit.
// Only releases referenced by src/translationManifest.ts are included.
export type RedumpTarget = {
  release: string;
  serial: string;
  track: string;
  tracks: number;
  size: number;
  crc32: string;
  sha1: string;
};
export const redumpDatVersion = "2026.08.01";
export const redumpTargets: RedumpTarget[] = [
  {
    "release": "Baroque - Yuganda Mousou (Japan) (Genteiban)",
    "serial": "SLPM-86328",
    "track": "Baroque - Yuganda Mousou (Japan) (Genteiban) (Track 1).bin",
    "tracks": 1,
    "size": 646249632,
    "crc32": "144dabcd",
    "sha1": "91c379b48eba6cf55cb057c3f89bae23725cc85a"
  },
  {
    "release": "Germs - Nerawareta Machi (Japan)",
    "serial": "SLPS-02107",
    "track": "Germs - Nerawareta Machi (Japan).bin",
    "tracks": 1,
    "size": 190013376,
    "crc32": "b32d4a63",
    "sha1": "8ef1ed69c8f532d8e2ee91e1e4650b6a014ac2d4"
  },
  {
    "release": "Harmful Park (Japan)",
    "serial": "SLPS-00498",
    "track": "Harmful Park (Japan).bin",
    "tracks": 1,
    "size": 550443264,
    "crc32": "b1589bb4",
    "sha1": "fe44ca3ce8abd69a002cf304a1d7f99a16bbf1d6"
  },
  {
    "release": "Kowloon's Gate - Kowloon Fuusuiden (Japan) (Disc 1) (Byakko)",
    "serial": "SLPS-00706",
    "track": "Kowloon's Gate - Kowloon Fuusuiden (Japan) (Disc 1) (Byakko).bin",
    "tracks": 1,
    "size": 734129760,
    "crc32": "2107715c",
    "sha1": "d508793cb307ed31cc0433cad85a455c360b5233"
  },
  {
    "release": "Linda^3 Again (Japan)",
    "serial": "SCPS-10039",
    "track": "Linda^3 Again (Japan).bin",
    "tracks": 1,
    "size": 733153680,
    "crc32": "a8faaf83",
    "sha1": "a27a2f3e12cdb8a3d668ae40bba301bd4162646a"
  },
  {
    "release": "Mizzurna Falls (Japan)",
    "serial": "SLPS-01783",
    "track": "Mizzurna Falls (Japan).bin",
    "tracks": 1,
    "size": 399701232,
    "crc32": "a87f3497",
    "sha1": "c49b2a1203831165e63e1129cfe413d4d23d7656"
  },
  {
    "release": "Ore no Ryouri (Japan)",
    "serial": "SCPS-10099",
    "track": "Ore no Ryouri (Japan).bin",
    "tracks": 1,
    "size": 555166080,
    "crc32": "fd086dfa",
    "sha1": "4b9c493743017ab1a1dee7540888d03cd87b3f33"
  },
  {
    "release": "Paranoia Scape (Japan)",
    "serial": "SLPS-01375",
    "track": "Paranoia Scape (Japan) (Track 01).bin",
    "tracks": 1,
    "size": 96697776,
    "crc32": "925d447e",
    "sha1": "8344554bedaf1e4de8b9f871514b08c6b65d112d"
  },
  {
    "release": "Planet Laika (Japan)",
    "serial": "SLPM-86264",
    "track": "Planet Laika (Japan).bin",
    "tracks": 1,
    "size": 647124576,
    "crc32": "8d90b6cd",
    "sha1": "0c60406f5322431558da857f730d302891bac4dc"
  },
  {
    "release": "Racing Lagoon (Japan, Asia)",
    "serial": "SLPS-02038",
    "track": "Racing Lagoon (Japan, Asia).bin",
    "tracks": 1,
    "size": 748634544,
    "crc32": "22f8241c",
    "sha1": "d7799aaa009ca173d4b538691e0156163eb458e3"
  },
  {
    "release": "Remote Control Dandy (Japan)",
    "serial": "SLPS-02243",
    "track": "Remote Control Dandy (Japan) (Track 1).bin",
    "tracks": 1,
    "size": 437662512,
    "crc32": "f0d42361",
    "sha1": "9b5e692e203d6195859b997ba4ddb4a3bb5bfcf5"
  },
  {
    "release": "Tobal 2 (Japan, Asia)",
    "serial": "SLPM-86033",
    "track": "Tobal 2 (Japan, Asia).bin",
    "tracks": 1,
    "size": 669541488,
    "crc32": "45c9ad06",
    "sha1": "541ed99ee007f2bb37c08da27ca3f52d8868fa84"
  }
];
